- id: '1606560288972'
  alias: Front Door Motion
  description: ''
  trigger:
  - platform: state
    entity_id: group.entry_motion_detection
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - scene: scene.front_yard_lights
  mode: single
- id: '1606646360023'
  alias: Butlers Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: dc0e10b59f39f0804f17071108bb3080
    entity_id: binary_sensor.pantry_motion_sensor_motion
    domain: binary_sensor
  condition: []
  action:
  - scene: scene.butler_s_pantry
  mode: restart
- id: '1606647092536'
  alias: Master Robe Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 85c1e345b42f59f0a6c3d69e2cc2988e
    entity_id: binary_sensor.master_robe_motion_sensor_motion
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - scene: scene.master_robe_on
  mode: single
- id: '1606818882600'
  alias: Lock Doors at Night
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: 00:00:00
  condition:
  - type: is_not_open
    condition: device
    device_id: 38d2423f99617b6902543a7c29606298
    entity_id: binary_sensor.front_door_sensor_contact
    domain: binary_sensor
  action:
  - device_id: b502a513626ef0c34853d3772505f6d0
    domain: lock
    entity_id: lock.front_door
    type: lock
  - device_id: fa1a40b843cdd263e4710b6f35052983
    domain: lock
    entity_id: lock.garage_entry
    type: lock
  mode: single
- id: '1607769525253'
  alias: Ensuite Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 7b55ba1713a77c879b7573fb3202bdc8
    entity_id: binary_sensor.ensuite_motion
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: light.ensuite_lights
    state: 'off'
  action:
  - scene: scene.ensuite_night_mode
  mode: single
- id: '1608018403580'
  alias: Turn on the stair lights when the sun is set
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - domain: light
    entity_id: light.stairs_down_1
    device_id: 21181ceb8b946eddc56054c8cb8eb018
    type: turn_on
    brightness_pct: 10
  mode: single
- id: '1608018493807'
  alias: Turn off the stair lights when the sun rises
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_off
    device_id: 21181ceb8b946eddc56054c8cb8eb018
    entity_id: light.stairs_down_1
    domain: light
  mode: single
- id: '1608762855139'
  alias: Garage Motion
  description: ''
  trigger:
  - platform: state
    entity_id: group.garage_motion_detection
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 460e83eed69589c8ac30e39531974ca2
    entity_id: light.light
    domain: light
    brightness_pct: 100
  mode: restart
- id: '1608772537185'
  alias: Close Garage after 1HR
  description: ''
  trigger:
  - platform: state
    entity_id: group.garage_motion_detection
    from: 'on'
    to: 'off'
    for: 01:00:00
  condition: []
  action:
  - device_id: 8c8da50538a89c6ba8065484d32caf0e
    domain: cover
    entity_id: cover.garage_door
    type: close
  mode: single
- id: '1608774341516'
  alias: Heater Tampering
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: ad756006a9a050e75bf1138df6245fac
    entity_id: sensor.living_temperature
    domain: sensor
    above: 22
  condition: []
  action:
  - service: notify.mobile_app_pixel_5
    data:
      message: Heater tampering
  - service: notify.notify
    data:
      message: Heater tampering
  mode: single
- id: '1609012948827'
  alias: Turn Sound Down Overnight
  description: ''
  trigger:
  - platform: time
    at: 00:07:30
  condition: []
  action:
  - scene: scene.sonos_volume_10
  mode: single
- id: '1609473133030'
  alias: Front Door No Motion
  description: ''
  trigger:
  - entity_id: group.entry_motion_detection
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  condition: []
  action:
  - scene: scene.front_yard_off
  mode: single
- id: '1609477935315'
  alias: Butlers No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: dc0e10b59f39f0804f17071108bb3080
    entity_id: binary_sensor.pantry_motion_sensor_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - scene: scene.butlers_pantry_off
  mode: single
- id: '1609478441059'
  alias: Master Robe No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 85c1e345b42f59f0a6c3d69e2cc2988e
    entity_id: binary_sensor.master_robe_motion_sensor_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - scene: scene.master_robe_off
  mode: single
- id: '1609478593120'
  alias: Ensuite No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 7b55ba1713a77c879b7573fb3202bdc8
    entity_id: binary_sensor.ensuite_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - scene: scene.ensuite_no_motion
  mode: single
- id: '1609479215257'
  alias: blueprint test
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '120'
      motion_entity: binary_sensor.ensuite_motion
      light_target:
        area_id: 82329dcf31079f47056a2539a1361d89
- id: '1609481861419'
  alias: Garage No Motion
  description: ''
  trigger:
  - platform: state
    entity_id: group.garage_motion_detection
    from: 'on'
    to: 'off'
    for: 00:10:00
  condition: []
  action:
  - type: turn_off
    device_id: 460e83eed69589c8ac30e39531974ca2
    entity_id: light.light
    domain: light
  mode: single
- id: '1609808177078'
  alias: Kid's Bathroom Fan On
  description: If bathroom lights turn on, turn on fan
  trigger:
  - platform: state
    entity_id: light.kid_s_bathroom
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: bdf6795fdf2ca50d1614d8f291ce42b1
    entity_id: switch.projector
    domain: switch
  mode: single
- id: '1609808226087'
  alias: Kid's Bathroom Fan Off
  description: ''
  trigger:
  - platform: state
    entity_id: light.kid_s_bathroom
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: bdf6795fdf2ca50d1614d8f291ce42b1
    entity_id: switch.projector
    domain: switch
  mode: single
- id: '1609816809823'
  alias: Guest Bathroom Motion Lights On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 66e144a7855774931a5890dc5ff97fe2
    entity_id: binary_sensor.guest_bathroom_motion_sensor_motion
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.guest_bath_lights
  mode: single
- id: '1609817172392'
  alias: Guest Bathroom No Motion Lights Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 66e144a7855774931a5890dc5ff97fe2
    entity_id: binary_sensor.guest_bathroom_motion_sensor_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.guest_bath_lights
  mode: single
- id: '1609817366568'
  alias: Kids Bathroom Motion Lights On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 051cb788a7ae46b9987ea7f452c5295a
    entity_id: binary_sensor.kids_bathroom_motion_sensor_motion
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.kid_s_bathroom
  mode: single
- id: '1609817421503'
  alias: Kids Bathoom No Motion Lights Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 051cb788a7ae46b9987ea7f452c5295a
    entity_id: binary_sensor.kids_bathroom_motion_sensor_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.kid_s_bathroom
  mode: single
- id: '1609954309558'
  alias: Kids TV On Holidays
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.christmas_lights
  - service: switch.turn_on
    data: {}
    entity_id: switch.kids_power
  mode: single
- id: '1609954308322'
  alias: Kids TV On Holidays
  description: Turn on at 6.20am
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.christmas_lights
  - service: switch.turn_on
    data: {}
    entity_id: switch.kids_power
  mode: single
- id: '1609972159052'
  alias: Turn off Kids TV at 9am
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.christmas_lights
  - service: switch.turn_off
    data: {}
    entity_id: switch.kids_power
  mode: single
