# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include includes/customize.yaml

# System Includes
recorder: !include includes/recorder.yaml
influxdb: !include includes/influxdb.yaml
logger: !include includes/logger.yaml
# remote: !include includes/remotes.yaml

# Text to speech
tts:
  - platform: google_translate

# Includes
device_tracker: !include includes/device_trackers.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include includes/lights.yaml
input_number: !include includes/input_numbers.yaml
input_boolean: !include includes/input_boolean.yaml
input_text: !include includes/input_text.yaml
switch: !include includes/switches.yaml
cover: !include includes/covers.yaml
fan: !include includes/fans.yaml
climate: !include includes/climate.yaml
smartir:
media_player: !include includes/media_player.yaml
notify: !include includes/notify.yaml
binary_sensor: !include includes/binary_sensors.yaml
lifx: !include includes/lifx.yaml
nest: !include includes/nest.yaml
sensor: !include includes/sensors.yaml
# ecovacs: !include includes/ecovacs.yaml
# person: !include includes/persons.yaml # Double up of people, add devices in config

# Reset LinkTap Rest Command
rest_command:
  reset_linktap_gw:
    url: "http://192.168.3.208/index.shtml?flag=0"
# Requirements for UI Lovelace Minimalist
browser_mod:
