- platform: template
  sensors:
    sonos_group:
      friendly_name: "Sonos Group"
      value_template: "{{ is_state('binary_sensor.sonos_group', 'on') }}"
- platform: workday
  country: AU
  province: VIC
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
