- platform: climate_group
  name: "Kid's Rooms"
  temperature_unit: C # default to celsius, 'C' or 'F'
  entities:
    - climate.mabel
    - climate.sidney
- platform: climate_group
  name: "All Heating"
  temperature_unit: C # default to celsius, 'C' or 'F'
  entities:
    - climate.living
    - climate.living_front
    - climate.master_bed
    - climate.rumpus_2
    - climate.office
    - climate.mabel
    - climate.sidney
    - climate.guest_room
    # - climate.kid_s_rooms
- platform: climate_group
  name: "All Cooling"
  temperature_unit: C # default to celsius, 'C' or 'F'
  entities:
    - climate.living_cooling
    - climate.master_cooling
    - climate.office_cooling
