- platform: template
  switches:
    back_yard_front:
      friendly_name: Sprinkler Front
      value_template: "{{ is_state('binary_sensor.back_yard_front_station_running', 'on') }}"
      turn_on:
        - service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.back_yard_front_station_running
            # Run seconds uses the input_number below.
            run_seconds: "{{ ((states('input_number.back_yard_all_stations_minutes') | float) * 60) | int }}"
        - service: switch.turn_on
          target:
            entity_id: switch.ff424023004b1200_water_switch
      turn_off:
        - service: opensprinkler.stop
          data:
            entity_id: binary_sensor.back_yard_front_station_running
        - service: switch.turn_off
          target:
            entity_id: switch.ff424023004b1200_water_switch
    back_yard_rear:
      friendly_name: Back Yard Rear
      value_template: "{{ is_state('binary_sensor.back_yard_rear_station_running', 'on') }}"
      turn_on:
        - service: opensprinkler.run
          data_template:
            entity_id: binary_sensor.back_yard_rear_station_running
            # Run seconds uses the input_number below.
            run_seconds: "{{ ((states('input_number.back_yard_all_stations_minutes') | float) * 60) | int }}"
        - service: switch.turn_on
          target:
            entity_id: switch.ff424023004b1200_water_switch
      turn_off:
        - service: opensprinkler.stop
          data:
            entity_id: binary_sensor.back_yard_rear_station_running
        - service: switch.turn_off
          target:
            entity_id: switch.ff424023004b1200_water_switch
    sonos_group:
      friendly_name: Sonos Group
      value_template: "{{ is_state('input_boolean.sonos_group', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.sonos_butlers_join_living
          data_template:
            entity_id: input_boolean.sonos_group
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.sonos_group
      turn_off:
        - service: script.turn_on
          entity_id: script.sonos_butlers_leave_living
          data:
            entity_id: input_boolean.sonos_group
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.sonos_group
#    festoon_switch:
#      friendly_name: Festoon Switch
#      turn_on:
#        service: system_log.write
#        data:
#          message: "Festoon Switch On"
#      turn_off:
#        service: system_log.write
#        data:
#          message: "Festoon Switch Off"
#- platform: broadlink
#  host: 192.168.2.156
#  mac: 24:df:a7:f9:1c:cd
#  switches:
#    - name: Fireplace
#      command_on: scCGAgCfBgAlDwsdDBAYHRkQCx0ZEAsQCxIlHhgeGBALHQsQGR4KEBgXJR4LEAsQChEKEQsQGB4KEBkQChMlHgsQCxAYHgsQChEYHgoRFxUlEAseGB4YEAsQCx4KERgQCxUlEAsQCxALHQsQCxALEBgeCxAYEyUdCxEYEAsRCRELHRkdGBEKqyYRCh4LEBgeGBEKHhgRChALEiUeGB4YEAseCxAYHQwQGBQlHgsQCxALEAsQCxAYHgsQGBALEiYdCxALEBgeCxALEBgeCxAYEyUQCx0ZHRkQCxALHgoRGBAKEyUQCxALEQoeChALEAsQGR4KEBkSJR4KERgQCxALEQoeGB4YEAquJhALHgsQGB0ZEAsdGRALEAsRJh4YHRkQCx4KERgdCxAYEiYeCw8LEQoQCxALEBkdCxEXEQoTJR4KEQoQGR0MEAoQGR0LEBgWJRAKHxceGRAKEQoeCxAYEQoTJRALEAsQCx4KEAsQCxAZHQsQGBImHgoRFxELEAsQCx0YHxgQCqsmEAseCxAYHhgQCx4YEAsQCxYlHhgeGBEKHgsQGB4LEBgSJR4LEAsQCxALEAsQGB4LEBgQCxUkHgsQCxAYHgsQCxAYHQsRGBQmEAseGB0ZEAsQCx0LEBgQCxMlEQoQCxALHgoQCxALEBkdCxAYEyUeChAZEAsQCxALHhgdGRAKrCYQCh4LEBgeGBALHhgQCxALFCYdGR0ZEAseChEYHQsQGBImHgoRChALEAsQCxAZHQsQGBEKEiYeChALEBkeChEKERgdCxAYEiYRCh4YHhgQCxALHgsQGBALEiURCw8LEQseChALEAsQGB0LEBkUJh4KEBgRCxAKEQoeGB4YEQoABdw=
#      command_off: scCaAgCfBgAoDQ0bDg0bGxsODRwaDg0ODRAnHBocGg8MHQsPGR4LDxoRJR4LEAsQCxALEAsQGB4LEBgQCxImHQsQCxEYHQsQCxALEAsQGRAKFSYQCx0YHhkQCxALHQsRFxALEiYQCxALHQsQCxALEQsPCxALEAsQGREmHgsPGRALEAsQCx4YHhgQC6smEAseCw8ZHRkQCx0ZEAsQCxQmHRkdGRALHQsQGR0LEBgSJh4KEQoQCxALEAsQGR0LEBgQCxMlHgsQCxAYHgsQCxALEAsQGBALEiURCh4YHhgRChELHQsQGBALEiYQCxALHQsQCxEKEAsQCxALEAsQGBUlHgsQGBEKEAwQCh4YHhgRCqwlEAseCxAYHhgQCx4YEAsQCxImHRocGBELHQsQGB4LEBgSJR4LEAsQCxALEAsQGR0LEBgQCxUlHgsQCxAYHgsQCxALEAsQGBALEiYQCx4YHhgQCxALHQsQGRALEiUQCxALHgsQCxALEAsQCxALDwsRGBIlHgsQGBALEAsQCx4YHhgQC7AlEAseCxAYHhkPEBkYEAsQCxImHRkdGBELHQsQGR0LEBgUJR4LEAsQCxALEAsQGB4LEBgQCxUlHgsQCxAYHgsQCxALEAsQGBALEiURCh4ZHRkQChEKHgsQGBALEyUQCxALHgsPCxALEAsQCxAMDwsQGBImHgsQGBALEAsQCx4YHhgQC64lEQoeCxAZHRkQCh4YEAsQCxMlHRkdGRALHQsQGR0LEBgSJh4KEAsQDA8LEAsQGR0LEBkQChImHgsQChAZHgsQCxALDwwPGRALEiURCh4ZHRgRChEKHgsQGBALFSURChEKHgsQCxALEAsQCxALEAsQGBIlHgsQGBEKEAsRCh4YHhgQCwAF3AAAAAAAAAAAAAAAAA==
#    - name: Fireplace High
#      command_on: scCQAgCfBgAnDQ4bDQ4aHBoPDBwaDwwPDBEmHRkdGRALHQwPGR0LEBkWJR0MDwwQCxALEAsPGR4LDxkQCxIlHgsQCxAYHgsQCxAYHgsQGBQlEQoRCh4LEBkQChEKHgsQGBEKFSURChEKEQoeCxALEAsQGB4LEBgSJREKHwoQGBEKHhgRCx0YEQqsJhAKHgsQGB4ZEAoeGBALEAsSJh0YHhkQCx0LEBkdCxAYFSUeCxALEAsQCxALEBgeCxAYEAsSJh4KEAsQGR0LEAsRFx4LEBgTJRALEAseCxAYEAsQCx4LEBgQCxIlEQoRChEKHgsQCxALEBgeCxAYEiURCh4LEBgRCh4YEQoeGBEKriYQCx0MEBgdGRALHRkQCxALEiUeGB4YEQoeCxAYHgsPGRIlHgsQCxALEAsQCxAYHgsQGBALEiYdCxALEBkdCxALEBgeCxAYFSURChEKHgsQGBEKEQoeCxAYEQoSJhEKEAsRCh0MEAoRChEYHQsRFxMlEAseCxAYEQoeGBALHhgQC6smEAsdCxAZHRkQCx0ZEAsQCxYlHhgeGBEKHgsQGB4LEBgSJR4LEAsQCxALEAsQGB4LEBgQCxQmHQsQCxAYHgsQCxAYHgsQGBUlEQoRCh4LEBgRChEKHgsQGBALEiYQCxALEAseChEKEAsQGR0LEBgTJRALHgoRGBALHhgQCx4YEAurJhALHgoQGR0ZEAsdGRALEAsUJh0YHhgRCh4LEBgeCxAYEiYdCxALEAsQCxALEBgeCxAYEQoTJR0LEQoQGR4KEQoQGR4KEBgTJREKEQoeCxAYEQoRCh4LEBgQCxImEAoRCxALHgoQCxALERgdCxAYFSUQCx4LEBkQCh4YEQoeGBEKAAXc
#      command_off: scCaAgCfBgAoDQ0bDg0bGxsODRwaDg0ODRAnHBocGg8MHQsPGR4LDxoRJR4LEAsQCxALEAsQGB4LEBgQCxImHQsQCxEYHQsQCxALEAsQGRAKFSYQCx0YHhkQCxALHQsRFxALEiYQCxALHQsQCxALEQsPCxALEAsQGREmHgsPGRALEAsQCx4YHhgQC6smEAseCw8ZHRkQCx0ZEAsQCxQmHRkdGRALHQsQGR0LEBgSJh4KEQoQCxALEAsQGR0LEBgQCxMlHgsQCxAYHgsQCxALEAsQGBALEiURCh4YHhgRChELHQsQGBALEiYQCxALHQsQCxEKEAsQCxALEAsQGBUlHgsQGBEKEAwQCh4YHhgRCqwlEAseCxAYHhgQCx4YEAsQCxImHRocGBELHQsQGB4LEBgSJR4LEAsQCxALEAsQGR0LEBgQCxUlHgsQCxAYHgsQCxALEAsQGBALEiYQCx4YHhgQCxALHQsQGRALEiUQCxALHgsQCxALEAsQCxALDwsRGBIlHgsQGBALEAsQCx4YHhgQC7AlEAseCxAYHhkPEBkYEAsQCxImHRkdGBELHQsQGR0LEBgUJR4LEAsQCxALEAsQGB4LEBgQCxUlHgsQCxAYHgsQCxALEAsQGBALEiURCh4ZHRkQChEKHgsQGBALEyUQCxALHgsPCxALEAsQCxAMDwsQGBImHgsQGBALEAsQCx4YHhgQC64lEQoeCxAZHRkQCh4YEAsQCxMlHRkdGRALHQsQGR0LEBgSJh4KEAsQDA8LEAsQGR0LEBkQChImHgsQChAZHgsQCxALDwwPGRALEiURCh4ZHRgRChEKHgsQGBALFSURChEKHgsQCxALEAsQCxALEAsQGBIlHgsQGBEKEAsRCh4YHhgQCwAF3AAAAAAAAAAAAAAAAA==

