# Non-template switches (group, broadlink, etc.)
- platform: group
  name: Adaptive Lights (Master Switch)
  entities:
    - switch.adaptive_lighting_bathroom_cabinets
    - switch.adaptive_lighting_bathroom_default
    - switch.adaptive_lighting_default
    - switch.adaptive_lighting_fireplace_lights_tv
    - switch.adaptive_lighting_kids
    - switch.adaptive_lighting_kids_bathroom_cabinet
    - switch.adaptive_lighting_kids_bedside_lamps
    - switch.adaptive_lighting_master
    - switch.adaptive_lighting_sid_s_lamps
    - switch.adaptive_lighting_stairs_down
    - switch.adaptive_lighting_walk_in_robe

# The smartir integration in fans.yaml handles the fireplace now.
